# syntax=docker/dockerfile:1

FROM python

WORKDIR /app
RUN pip install mysql-connector-python
RUN pip install flask
RUN pip install flask-mysqldb
COPY . .

CMD ["python", "-m" , "flask", "run", "--host=0.0.0.0"]