apiVersion: apps/v1
kind: Deployment
metadata:
  name: busy-williams
  labels:
    app: busy-williams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy-williams
  template:
    metadata:
      labels:
        app: busy-williams
    spec:
      containers:
      - name: busy-williams
        image: hitendramhatre/my-react-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: busy-williams
spec:
  selector:
    app: busy-williams
  ports:
  - name: http
    port: 80
    targetPort: 3000
  type: NodePort
