apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app-depl
spec:
  selector:
    matchLabels:
      app: react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: madhavisuratkar/react-app
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-app-srv
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: my-app
      port: 80
      targetPort: 3000
