version: "3.8"
services:
  springboot-app:
    container_name: spring-app
    restart: always
    build:
      context: .
    image: spring-compose-image
    ports:
      - "8080:8080"
      
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: madhavi
      
  mysqldb:
    container_name: mysqldb
    image: mysql
   
   
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: E-krushi
      MYSQL_ROOT_PASSWORD: madhavi
   
