apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: hitendramhatre/mysql:8.0.30
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: etour
        - name: MYSQL_PASSWORD
          value: "1234"
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb-service
spec:
  selector:
    app: mysqldb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mysqldb-route
spec:
  to:
    kind: Service
    name: mysqldb-service
  port:
    targetPort: mysql
  tls:
    termination: edge
