apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: hitendramhatre/springbootmysql
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysqldb-service:3306/etour?useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "1234"
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: server-route
spec:
  to:
    kind: Service
    name: server-service
  port:
    targetPort: http
  tls:
    termination: edge
