FROM python:3.11
WORKDIR /app
EXPOSE 5000
RUN pip install flask
RUN pip install mysql-connector
RUN pip install flask_mysqldb
ENV MYSQL_DATABASE=CRUD
ENV MYSQL_HOST=LOCALHOST:3306
ENV MYSQL_USER=ROOT
ENV MYSQL_PASSWORD=Rohan@91196
COPY . . 
CMD ["python","app.py"]