# -*- coding: utf-8 -*-
"""Palindrome

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Oh76X65--sa3gwsq8noMM4KK_KrkrjW
"""

str1=input("Enter the string to be checked ").lower()
str2=str1[::-1]
if str1==str2:
  print("String is palindrome ") 
else:
  print("String is not palindrome ")

